//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sculptor.EDBEntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAspect
    {
        public System.Guid ID { get; set; }
        public int Project_ID { get; set; }
        public string AspectName { get; set; }
        public string Description { get; set; }
        public Nullable<bool> HardIO { get; set; }
        public Nullable<bool> ExtIO { get; set; }
        public Nullable<bool> PLCTag { get; set; }
        public Nullable<bool> SCADATag { get; set; }
        public Nullable<bool> AlarmTag { get; set; }
        public Nullable<bool> TrendTag { get; set; }
        public string Note { get; set; }
    }
}
