//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sculptor.EDBEntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProperty
    {
        public System.Guid ID { get; set; }
        public int Project_ID { get; set; }
        public Nullable<System.Guid> Parent_ID { get; set; }
        public string PropertyName { get; set; }
        public string Description { get; set; }
        public string Value { get; set; }
        public Nullable<int> PropertyType_ID { get; set; }
        public string Aspect { get; set; }
        public string Attribute1 { get; set; }
        public string Attribute2 { get; set; }
        public string Attribute3 { get; set; }
    }
}
