//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sculptor.EDBEntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRequirement
    {
        public System.Guid ID { get; set; }
        public int Project_ID { get; set; }
        public string ArticleNo { get; set; }
        public string ArticleHeader { get; set; }
        public string Content { get; set; }
        public Nullable<int> RequirementType_ID { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastChanged { get; set; }
        public string LastChangedBy { get; set; }
        public string Version { get; set; }
        public Nullable<System.Guid> Parent_ID { get; set; }
    }
}
