//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sculptor.EDBEntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTemplateAssociation
    {
        public System.Guid ID { get; set; }
        public int Project_ID { get; set; }
        public System.Guid Template_ID { get; set; }
        public System.Guid Association_ID { get; set; }
        public string Value { get; set; }
        public string AssociationType { get; set; }
    }
}
