//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sculptor.EDBEntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTemplateRequirement
    {
        public int Project_ID { get; set; }
        public System.Guid Template_ID { get; set; }
        public System.Guid Requirement_ID { get; set; }
        public string RequirementType { get; set; }
        public Nullable<bool> PreFATOk { get; set; }
        public Nullable<bool> FATOk { get; set; }
        public Nullable<bool> SATOk { get; set; }
        public Nullable<System.DateTime> FATDate { get; set; }
        public Nullable<System.DateTime> SATDate { get; set; }
        public string PreFATBy { get; set; }
        public string FATBy { get; set; }
        public string SATBy { get; set; }
    }
}
